%.min.js : %.js
	mjs <$< >$@

all: \
	anazitisi.min.js \
	arena.min.js \
	cpanel.min.js \
	efoplismos.min.js \
	enimerosi.min.js \
	epanel.min.js \
	kinisi.min.js \
	kinisi.min.min.js \
	kitapi.min.js \
	online.min.js \
	partida.min.js \
	peximo.min.js \
	peximo.min.min.js \
	profinfo.min.js \
	prosklisi.min.js \
	sizitisi.min.js \
	skiniko.min.js
